display_name: Nya LoCyanFrp!
package_name: nyanana
maintainer:
  name: Muska-Ami
  email: xmcn@1l1.icu
co_authors:
  - '\n'
priority: optional
section: x11
installed_size: 6604
essential: false
icon: asset/icon/icon.png

postinstall_scripts:
  - 'echo "Nya LoCyanFrp! Powered by love."'
postuninstall_scripts: []

keywords:
  - NyaLCF
  - Nya LoCyanFrp!
  - nyanana
  - LoCyanFrp

generic_name: NyaLCF

categories:
  - Network

startup_notify: true
