# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Build Application
        run: flutter build windows
      - uses: actions/upload-artifact@v3
        with:
          name: Windows Artifact
          path: build
  
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - uses: ashutoshvarma/setup-ninja@v1.1
      
      - name: Install dependencies
        run: flutter pub get
      - name: Build Application
        run: flutter build linux
        
      - uses: actions/upload-artifact@v3
        with:
          name: Linux Artifact
          path: build

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      - name: Build Application
        run: flutter build macos
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS Artifact
          path: build
